services:
  raisehub-database:
    image: mateogonzalezz/blockchain_raisehub_database
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: blockchain_raisehub_database
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  raisehub-backend:
    image: mateogonzalezz/blockchain_raisehub_backend
    container_name: blockchain_raisehub_backend
    environment:
      - JWT_SECRET=E91E158E4C6656F68B165H1C316766DE98D2AD6EF3BFB44F78E9CFCDF5
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=25DX0MR2CG
    ports:
      - 8080:8080
    depends_on:
      raisehub-database:
        condition: service_healthy

  nameless-frontend:
    image: mateogonzalezz/blockchain_raisehub_frontend
    container_name: blockchain_raisehub_frontend
    environment:
      - AWS_BUCKET_NAME=<value>
      - AWS_BUCKET_REGION=<value>
      - AWS_ACCESS_KEY=<value>
      - AWS_SECRET_ACCESS_KEY=<value>
    ports:
      - 3000:3000
    depends_on:
      - raisehub-backend

volumes:
  mysql-data:


name: blockchain-raisehub-application
